version: '3.7'

services:
  api:
    
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - '5000:5000'
    environment:
      - FLASK_APP=api.py
      - FLASK_DEBUG=0
      - 'RUN=flask run --host=0.0.0.0 --port=5000'
    command: flask run --host=0.0.0.0 --port=5000
  ui:
    depends_on: 
      - api
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - '80:80'
    
