version: '3.7'

services:
  ui:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - '80:80'
  api:
    build:
      context: .
      dockerfile: ./backend/expensereport-api/Dockerfile
    ports:
      - '81:80'