version: '3.7'

services:
  ui:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - '80:80'
  api:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - '5000:5000'
    volumes:
      - ./backend/uploads:/app/uploads